server:
  port: 8080
spring:
  main:
    #允许bean定义覆盖配置项
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names:
        master, slave
      #主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.130.125.153:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: WisdomTree1221
       #从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://123.56.245.1:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: WisdomTree1221
    masterslave:
        #读写分离配置
        load-balance-algorithm-type: round_robin #轮询
        #最终的数据源名称(bean的名字)
        name: dataSource
        #主库数据源名称
        master-data-source-name: master
        #从库数据源名称列表,多个逗号分割
        slave-data-source-names: slave
    props:
        sql:
          show: true #开启SQL显示,默认false

  #设置spring cache的底层缓存产品
  cache:
    redis:
      time-to-live: 180000 #设置缓存过期时间
  application:
    #指定应用的名称（每个项目启动都是一个应用），不指定就默认
    name: Reggie
    #redis的配置信息
  redis:
    host: 8.130.125.153
#    host: localhost
    port: 6379
    #最多获取数
    lettuce:
      pool:
        max-active: 8
        max-wait: 8
        max-idle: 8
        min-idle: 0
    database: 1
    password: 12345
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: ASSIGN_ID
  #自定义变量
Reggie:
  #定义图片路径，后期方便维护，CommonController中使用了
  path: /usr/local/reggie/photos
